// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjADU53lh8Lno1etmKPaPs3Igef28JA4k',
    appId: '1:194653695398:web:f1f750a684377657b5f367',
    messagingSenderId: '194653695398',
    projectId: 'milkyway-a053f',
    authDomain: 'milkyway-a053f.firebaseapp.com',
    databaseURL: 'https://milkyway-a053f-default-rtdb.firebaseio.com',
    storageBucket: 'milkyway-a053f.appspot.com',
    measurementId: 'G-SCW9H20PYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqlgDkzKwIquL10ODSUrmXAtgPsnVxWjk',
    appId: '1:194653695398:android:c4352b7dd0f356c6b5f367',
    messagingSenderId: '194653695398',
    projectId: 'milkyway-a053f',
    databaseURL: 'https://milkyway-a053f-default-rtdb.firebaseio.com',
    storageBucket: 'milkyway-a053f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWeMcPtPytgvv7MIwxOhO2V8QuuS2rHPU',
    appId: '1:194653695398:ios:84ddca3f82bdad9ab5f367',
    messagingSenderId: '194653695398',
    projectId: 'milkyway-a053f',
    databaseURL: 'https://milkyway-a053f-default-rtdb.firebaseio.com',
    storageBucket: 'milkyway-a053f.appspot.com',
    iosBundleId: 'com.example.milkyway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWeMcPtPytgvv7MIwxOhO2V8QuuS2rHPU',
    appId: '1:194653695398:ios:84ddca3f82bdad9ab5f367',
    messagingSenderId: '194653695398',
    projectId: 'milkyway-a053f',
    databaseURL: 'https://milkyway-a053f-default-rtdb.firebaseio.com',
    storageBucket: 'milkyway-a053f.appspot.com',
    iosBundleId: 'com.example.milkyway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjADU53lh8Lno1etmKPaPs3Igef28JA4k',
    appId: '1:194653695398:web:aa9419717be3745fb5f367',
    messagingSenderId: '194653695398',
    projectId: 'milkyway-a053f',
    authDomain: 'milkyway-a053f.firebaseapp.com',
    databaseURL: 'https://milkyway-a053f-default-rtdb.firebaseio.com',
    storageBucket: 'milkyway-a053f.appspot.com',
    measurementId: 'G-GBCMQBL8MP',
  );

}